using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace InteractServer.Utils
{
    public static class Midi
    {
        public static Dictionary<int, string> ControllerNames = new Dictionary<int, string>();

        static Midi()
        {
            ControllerNames.Add(0, "Bank Select");
            ControllerNames.Add(1, "Modulation Wheel");
            ControllerNames.Add(2, "Breath Controller");
            ControllerNames.Add(3, "");
            ControllerNames.Add(4, "Foot Controller");
            ControllerNames.Add(5, "Portamento Time");
            ControllerNames.Add(6, "Data Entry MSB");
            ControllerNames.Add(7, "Channel Volume");
            ControllerNames.Add(8, "Balance");
            ControllerNames.Add(9, "");
            ControllerNames.Add(10, "Pan");
            ControllerNames.Add(11, "Expression Controller");
            ControllerNames.Add(12, "Effect Control 1");
            ControllerNames.Add(13, "Effect Control 2");
            ControllerNames.Add(14, "");
            ControllerNames.Add(15, "");
            ControllerNames.Add(16, "General Purpose Controller 1");
            ControllerNames.Add(17, "General Purpose Controller 2");
            ControllerNames.Add(18, "General Purpose Controller 3");
            ControllerNames.Add(19, "General Purpose Controller 4");
            ControllerNames.Add(20, "");
            ControllerNames.Add(21, "");
            ControllerNames.Add(22, "");
            ControllerNames.Add(23, "");
            ControllerNames.Add(24, "");
            ControllerNames.Add(25, "");
            ControllerNames.Add(26, "");
            ControllerNames.Add(27, "");
            ControllerNames.Add(28, "");
            ControllerNames.Add(29, "");
            ControllerNames.Add(30, "");
            ControllerNames.Add(31, "");
            ControllerNames.Add(32, "LSB for Control 0 (Bank Select)");
            ControllerNames.Add(33, "LSB for Control 1 (Modulation Wheel)");
            ControllerNames.Add(34, "LSB for Control 2 (Breath Controller)");
            ControllerNames.Add(35, "LSB for Control 3 (Undefined)");
            ControllerNames.Add(36, "LSB for Control 4 (Foot Controller)");
            ControllerNames.Add(37, "LSB for Control 5 (Portamento Time)");
            ControllerNames.Add(38, "LSB for Control 6 (Data Entry)");
            ControllerNames.Add(39, "LSB for Control 7 (Channel Volume)");
            ControllerNames.Add(40, "LSB for Control 8 (Balance)");
            ControllerNames.Add(41, "LSB for Control 9 (Undefined)");
            ControllerNames.Add(42, "LSB for Control 10 (Pan)");
            ControllerNames.Add(43, "LSB for Control 11 (Expression Controller)");
            ControllerNames.Add(44, "LSB for Control 12 (Effect Control 1)");
            ControllerNames.Add(45, "LSB for Control 13 (Effect Control 2)");
            ControllerNames.Add(46, "LSB for Control 14 (Undefined)");
            ControllerNames.Add(47, "LSB for Control 15 (Undefined)");
            ControllerNames.Add(48, "LSB for Control 16 (General Purpose Controller 1)");
            ControllerNames.Add(49, "LSB for Control 17 (General Purpose Controller 2)");
            ControllerNames.Add(50, "LSB for Control 18 (General Purpose Controller 3)");
            ControllerNames.Add(51, "LSB for Control 19 (General Purpose Controller 4)");
            ControllerNames.Add(52, "LSB for Control 20 (Undefined)");
            ControllerNames.Add(53, "LSB for Control 21 (Undefined)");
            ControllerNames.Add(54, "LSB for Control 22 (Undefined)");
            ControllerNames.Add(55, "LSB for Control 23 (Undefined)");
            ControllerNames.Add(56, "LSB for Control 24 (Undefined)");
            ControllerNames.Add(57, "LSB for Control 25 (Undefined)");
            ControllerNames.Add(58, "LSB for Control 26 (Undefined)");
            ControllerNames.Add(59, "LSB for Control 27 (Undefined)");
            ControllerNames.Add(60, "LSB for Control 28 (Undefined)");
            ControllerNames.Add(61, "LSB for Control 29 (Undefined)");
            ControllerNames.Add(62, "LSB for Control 30 (Undefined)");
            ControllerNames.Add(63, "LSB for Control 31 (Undefined)");

            ControllerNames.Add(64, "Damper Pedal on/off (Sustain)");
            ControllerNames.Add(65, "Portamento On/Off");
            ControllerNames.Add(66, "Sostenuto On/Off");
            ControllerNames.Add(67, "Soft Pedal On/Off");
            ControllerNames.Add(68, "Legato Footswitch");
            ControllerNames.Add(69, "Hold 2");
            ControllerNames.Add(70, "Sound Controller 1 (default: Sound Variation)");
            ControllerNames.Add(71, "Sound Controller 2 (default: Timbre)");
            ControllerNames.Add(72, "Sound Controller 3 (default: Release Time)");
            ControllerNames.Add(73, "Sound Controller 4 (default: Attack Time)");
            ControllerNames.Add(74, "Sound Controller 5 (default: Brightness)");
            ControllerNames.Add(75, "Sound Controller 6 (default: Decay Time)");
            ControllerNames.Add(76, "Sound Controller 7 (default: Vibrato Rate)");
            ControllerNames.Add(77, "Sound Controller 8 (default: Vibrato Depth)");
            ControllerNames.Add(78, "Sound Controller 9 (default: Vibrato Delay)");
            ControllerNames.Add(79, "Sound Controller 10 (default: Undefined)");
            ControllerNames.Add(80, "General Purpose Controller 5");
            ControllerNames.Add(81, "General Purpose Controller 6");
            ControllerNames.Add(82, "General Purpose Controller 7");
            ControllerNames.Add(83, "General Purpose Controller 8");
            ControllerNames.Add(84, "Portamento Control");
            ControllerNames.Add(85, "");
            ControllerNames.Add(86, "");
            ControllerNames.Add(87, "");
            ControllerNames.Add(88, "High Resolution Velocity Prefix");
            ControllerNames.Add(89, "");
            ControllerNames.Add(90, "");
            ControllerNames.Add(91, "Effects 1 Depth");
            ControllerNames.Add(92, "Effects 2 Depth");
            ControllerNames.Add(93, "Effects 3 Depth");
            ControllerNames.Add(94, "Effects 4 Depth");
            ControllerNames.Add(95, "Effects 5 Depth");
            ControllerNames.Add(96, "Data Increment");
            ControllerNames.Add(97, "Data Decrement");
            ControllerNames.Add(98, "Non-Registered Parameter Number");
            ControllerNames.Add(99, "Non-Registered Parameter Number");
            ControllerNames.Add(100, "Registered Parameter Number");
            ControllerNames.Add(101, "Registered Parameter Number");
            ControllerNames.Add(102, "");
            ControllerNames.Add(103, "");
            ControllerNames.Add(104, "");
            ControllerNames.Add(105, "");
            ControllerNames.Add(106, "");
            ControllerNames.Add(107, "");
            ControllerNames.Add(108, "");
            ControllerNames.Add(109, "");
            ControllerNames.Add(110, "");
            ControllerNames.Add(111, "");
            ControllerNames.Add(112, "");
            ControllerNames.Add(113, "");
            ControllerNames.Add(114, "");
            ControllerNames.Add(115, "");
            ControllerNames.Add(116, "");
            ControllerNames.Add(117, "");
            ControllerNames.Add(118, "");
            ControllerNames.Add(119, "");
            ControllerNames.Add(120, "All Sound Off");
            ControllerNames.Add(121, "Reset All Controllers");
            ControllerNames.Add(122, "Local Control On/Off");
            ControllerNames.Add(123, "All Notes Off");
            ControllerNames.Add(124, "Omni Mode Off");
            ControllerNames.Add(125, "Omni Mode On");
            ControllerNames.Add(126, "Mono Mode On");
            ControllerNames.Add(127, "Poly Mode On");
        }
    }
}
