source "https://rubygems.org"
gemspec

gem 'wdm', '>= 0.1.0'

group :jekyll_plugins do 
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
    gem "jekyll-sitemap"
    gem "jekyll-paginate"
    gem "jekyll-algolia"
end